repos:
  - repo: https://github.com/arkinmodi/add-license-header
    rev: v2.4.0
    hooks:
      - id: add-license-header
        args:
          - --exit-zero-if-unsupported
          - --license-file
          - GPL-LICENSE.template
