name: Deploy and Notify Discord

# Trigger on every push to main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Notify Discord
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()  # ensures this runs even if previous steps fail
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "<@&1428209991990378517>"
          url: "https://github.com/Ethorbit/nzombies-chronicles"
